spring:
  application:
    name: commerce-system-api
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: user
    password: pass
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
mybatis:
  mapper-locations: classpath:/mapper/*.xml
jwt:
  key: 01234567890123456789012345678910
logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
