### JWT 발급? => username & password => form-data
POST {{baseUrl}}/auth/token
Content-Type: application/x-www-form-urlencoded

username = user &
password = pass

### JWT 발급? => username & password => json
POST {{baseUrl}}/auth/token
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

> {%
    client.test('', () => {
        client.assert(response.status === 200, "Expected 200 OK")

        client.global.set("accessToken", response.body.data.accessToken)
    })
%}

### JWT 검증
GET {{baseUrl}}/required-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEifQ.vAQCgmoB0N2k2Rozjz9J2kB7X9hmFFZtnmK7Rkh-fWg

{
  "username": "admin",
  "password": "pass"
}

### JWT refresh
< {%
    request.variables.set("refreshToken", "")
%}

GET {{baseUrl}}/auth/refresh
Authorization: Bearer {{refreshToken}}
