### Join(회원가입)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "tester",
  "password": "1234"
}

### 수정
POST {{baseUrl}}/users/102
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "tester",
  "password": "1234",
  "email": "tmfrl043@naver.com",
  "address": "2222.222-22"
}
